name: Plugin Check

on:
  push:
    branches: [trunk]
  pull_request:
  workflow_dispatch:

jobs:
  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run plugin check
        uses: WordPress/plugin-check-action@v1
        with:
          slug: user-teams
          exclude-directories: env
